name: DMZ Branch Validation and Main Fast-Forward

on:
  push:
    branches: [dmz]

env:
  NODE_VERSION: "22.11.0"

jobs:
  validate-dmz:
    name: Validate DMZ Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies for all starters
        run: |
          echo "Installing dependencies for all enabled starters..."

          # Install dependencies for each enabled starter
          if [ -d "examples/kit-nextjs-skate-park" ]; then
            echo "Installing dependencies for kit-nextjs-skate-park..."
            cd examples/kit-nextjs-skate-park
            npm install
            cd ../..
          fi

          if [ -d "examples/kit-nextjs-article-starter" ]; then
            echo "Installing dependencies for kit-nextjs-article-starter..."
            cd examples/kit-nextjs-article-starter
            npm install
            cd ../..
          fi

          if [ -d "examples/kit-nextjs-location-finder" ]; then
            echo "Installing dependencies for kit-nextjs-location-finder..."
            cd examples/kit-nextjs-location-finder
            npm install
            cd ../..
          fi

          if [ -d "examples/kit-nextjs-product-listing" ]; then
            echo "Installing dependencies for kit-nextjs-product-listing..."
            cd examples/kit-nextjs-product-listing
            npm install
            cd ../..
          fi

      - name: Lint and format check
        run: |
          echo "Running linting and formatting checks..."

          # Check each enabled starter
          for starter in examples/kit-nextjs-skate-park examples/kit-nextjs-article-starter examples/kit-nextjs-location-finder examples/kit-nextjs-product-listing; do
            if [ -d "$starter" ]; then
              echo "Checking $starter..."
              cd "$starter"
              
              # Run linting
              if npm run lint 2>/dev/null; then
                echo "✅ Linting passed for $starter"
              else
                echo "❌ Linting failed for $starter"
                exit 1
              fi
              
              # Check formatting
              if npm run format:check 2>/dev/null; then
                echo "✅ Formatting check passed for $starter"
              else
                echo "❌ Formatting check failed for $starter"
                echo "Run 'npm run prettier' to fix formatting issues"
                exit 1
              fi
              
              cd ../..
            fi
          done

      - name: Type checking
        run: |
          echo "Running TypeScript type checking..."

          # Check each enabled starter
          for starter in examples/kit-nextjs-skate-park examples/kit-nextjs-article-starter examples/kit-nextjs-location-finder examples/kit-nextjs-product-listing; do
            if [ -d "$starter" ]; then
              echo "Type checking $starter..."
              cd "$starter"
              
              # Generate Sitecore files first (needed for type checking)
              echo "Generating Sitecore configuration files..."
              npm run sitecore-tools:generate-map
              
              if npm run type-check 2>/dev/null; then
                echo "✅ Type checking passed for $starter"
              else
                echo "❌ Type checking failed for $starter"
                exit 1
              fi
              
              cd ../..
            fi
          done

      - name: Build all starters
        run: |
          echo "Building all enabled starters..."

          # Build each enabled starter
          for starter in examples/kit-nextjs-skate-park examples/kit-nextjs-article-starter examples/kit-nextjs-location-finder examples/kit-nextjs-product-listing; do
            if [ -d "$starter" ]; then
              echo "Building $starter..."
              cd "$starter"
              
              if npm run build; then
                echo "✅ Build successful for $starter"
              else
                echo "❌ Build failed for $starter"
                exit 1
              fi
              
              cd ../..
            fi
          done

      - name: Run tests
        run: |
          echo "Running tests for all starters..."

          # Test each enabled starter
          for starter in examples/kit-nextjs-skate-park examples/kit-nextjs-article-starter examples/kit-nextjs-location-finder examples/kit-nextjs-product-listing; do
            if [ -d "$starter" ]; then
              echo "Testing $starter..."
              cd "$starter"
              # Check if test script exists, if not fail the workflow
              if grep -q '"test"' package.json; then
                if npm test; then
                  echo "✅ Tests passed for $starter"
                else
                  echo "❌ Tests failed for $starter"
                  exit 1
                fi
              else
                echo "❌ No test script found for $starter - tests are mandatory"
                exit 1
              fi

              cd ../..
            fi
          done

  fast-forward-main:
    name: Fast-Forward Main Branch
    runs-on: ubuntu-latest
    needs: validate-dmz
    if: needs.validate-dmz.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fast-forward main to dmz
        run: |
          echo "Fast-forwarding main branch to dmz..."

          # Fetch latest changes
          git fetch origin

          # Check if dmz is ahead of main
          DMZ_COMMITS=$(git rev-list --count origin/main..origin/dmz)

          if [ "$DMZ_COMMITS" -gt 0 ]; then
            echo "DMZ is $DMZ_COMMITS commits ahead of main. Fast-forwarding..."
            
            # Fast-forward main to dmz
            git checkout main
            git merge --ff-only origin/dmz
            
            # Push the fast-forwarded main branch
            git push origin main
            
            echo "✅ Successfully fast-forwarded main to dmz"
          else
            echo "ℹ️ Main is already up to date with dmz"
          fi

      - name: Create success notification
        if: success()
        run: |
          echo "## ✅ DMZ Validation Successful" >> $GITHUB_STEP_SUMMARY
          echo "Main branch has been successfully fast-forwarded to dmz." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Validation Results:**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ All builds passed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ All tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Linting and formatting checks passed" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Type checking passed" >> $GITHUB_STEP_SUMMARY

  notify-failure:
    name: Notify Build Failure
    runs-on: ubuntu-latest
    needs: validate-dmz
    if: failure()

    steps:
      - name: Create failure notification
        run: |
          echo "## ❌ DMZ Validation Failed" >> $GITHUB_STEP_SUMMARY
          echo "The dmz branch failed validation and will not be fast-forwarded to main." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Next Steps:**" >> $GITHUB_STEP_SUMMARY
          echo "1. Review the failed checks above" >> $GITHUB_STEP_SUMMARY
          echo "2. Fix the issues in the dmz branch" >> $GITHUB_STEP_SUMMARY
          echo "3. Push the fixes to dmz branch" >> $GITHUB_STEP_SUMMARY
          echo "4. The validation will run automatically" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Alternative:** Use the 'Revert DMZ Branch' workflow to revert problematic commits." >> $GITHUB_STEP_SUMMARY
